### PR TITLE
added in spacing for colspan and updated effected tests

### PR DESCRIPTION
**Pull request by AidanCeney**
Update to add Colspan spacing to fix active issue

### CODE REVIEW

**Comment by shengwei66** [comment]
@AidanCeney I have used this PR branch to run the reprex example in [https://github.com/pharmaverse/tidytlg/issues/25](url). The rtf output is shown below:
TCM01

So the break issue in the spanning row line below ‘Active Study Agent’ and ‘x’ is fixed. However, the following issues still need to be addressed:

1. a solid line is needed to span across the entire page under the first row of the column header (i.e. start the solid line from the label column). The solid line in the above output starts from the column of 'col1'.
2. a feature to toggle underline or no underline for all column headers and all column spanning headers.
3. a feature to toggle a break or no break between underlines for column headers and column spanning headers.

**Comment by shengwei66** [comment]
@AidanCeney Thanks for the commits of adding the **firstcolumnborder** and **header_pad** parameters in the gentlg function. I re-ran the above reprex example with **firstcolumnborder = TRUE** and **header_pad = FALSE**, The updated rtf is shown below:
TCM01_r1

This fixed the solid line issue as mentioned in 1. However, the break in the underline between 'Active Study Agent' and 'x' is gone. Also the breaks in the underline between treatment groups are gone. Can we modify the two parameters you added to allow for the 2 features that I described above to toggle on and off the underline and break for column headers and spanning headers?

**Comment by AidanCeney** [comment]
@shengwei66 the header_pad boolean sets weather or not to create a space between column headers so if you set that to true the table should have the desired spacing between columns

**Comment by shengwei66** [comment]
@AidanCeney  Thanks for pointing out the **header_pad** boolean. I set it to true and the rtf is shown below:
TCM01_r2

This output has the breaks in the underlines of spanning headers we desired, but we need the underline below the column headers (standardized medication name, N=1, ...) without breaks. Can we modify the header_pad to only control the column header break, and add another parameter (maybe call it as spanheader_pad) to control the spanning header break?

**Comment by AidanCeney** [comment]
@shengwei66 Change header_pad to take a list of row indexs to decide which to add pad to run example run 
gentlg(huxme = tbl,
        orientation = "landscape",
        file = "TCM01",
        title = "Summary of Concomitant Medications",
        colspan = list(c("","Active Study Agent","Active Study Agent","Active Study Agent","x",""),
                       c("","Treatment 1","Treatment 2","Combined","Placebo","Total")),
        colheader = c(" Standardized medication name","N=1","N=1","N=2","N=1","N=3"),
        wcol = .30,
        header_pad = c(2,3),
        firstcolumnborder=TRUE
        )

**Comment by shengwei66** [comment]
@AidanCeney Thanks for the update. By specifying **header_pad = c(2,3)** and **firstcolumnborder=TRUE**, I am able to create the output below that meets our need:
TCM01_r3

However, we would still need the gentlg function to produce the old standard output (i.e., no underline in the first column, breaks for column headers and spanning headers). So following the logic of using the list input for header_pad, I am putting in the arguments of **header_pad = c(1, 2, 3)** and **firstcolumnborder = FALSE**. But the output produced has the solid line for the column headers:
TCM01_r4

So header_pad = c(1,2,3) only works for 2 and 3, not 1. Can this be fixed?

**Comment by AidanCeney** [comment]
@shengwei66 the row_pad includes row the tittle row in the index so if you want to add pad to the N=1 row you would have it be (2,3,4) I can adjust this to increment all values in the backend if you think its worth while

**Comment by shengwei66** [comment]
@AidanCeney Thanks for the explanation. I misunderstood the index list for the **header_pad** argument. As you pointed out, the title row has the index of 1. So the top spanning header (Active Study Agent, x) would have the index of 2. The 2nd spanning header (Treatment 1, Treatment 2, ...) would have the index of 3, The column header (N=1, ...) would have the index of 4. By specifying header_pad = c(2,3,4), I am able to get the expected output below:
TCM01_r5

I think that it's better to provide more documentation for the header_pad argument about the input index (especially the index starting as 1 in the title row). Can you please update the documentation?

Another feature we need is to toggle on/off the underline in the spanning header rows. For the new standard, we will need to remove the underline between Treatment 1 and N=1. Can you add an argument (maybe call it **colspan_line**) that can take a list input to turn on/off the underline?

**Review by shengwei66 — APPROVED** [review]

**Pull request merged**
